#!/bin/sh

# PROVIDE: zfs_encrypted
# REQUIRE: zfs
# KEYWORD: nostart shutdown

. /etc/rc.subr
name="zfs_encrypted"
rcvar="zfs_encrypted_enable"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

load_rc_config ${name}
: ${zfs_encrypted_enable:=no}

zfs_encrypted_geli_attach(){
	zpool="$1"
	eval "geli_devices=\${${name}_${zpool}_geli_devices}"

	for geli_device in ${geli_devices}
	do
		if [ -e ${geli_device}.eli ]
		then
			info "Skipping ${geli_device} as it appears to already be attached"
		else
			info "Attaching geli volume ${geli_device}" 
			eval "geli_flags=\${${name}_${zpool}_geli_flags}"
			if geli attach ${geli_flags} ${geli_device}
			then
				info "Successfully attached ${geli_device}"
			else
				err 1 "Failed to attach ${geli_device}"
			fi
		fi
	done
}

zfs_encrypted_zpool_exists(){
	zpool="$1"
	zpool status ${zpool} 2>1 > /dev/null
	return $?
}

zfs_encrypted_import_zpool(){
	zpool="$1"

	info "Importing zpool ${zpool}"
	# Set cachefile none to prevent automount on boot
	zpool import -o cachefile=none ${zpool}

	if zfs_encrypted_zpool_exists ${zpool}
	then
		info "Successfully imported zpool ${zpool}"
		zpool status ${zpool}
	else
		err 1 "Failed to import zpool ${zpool}"
	fi
}

zfs_encrypted_start_zpool(){
	zpool="$1"

	if zfs_encrypted_zpool_exists ${zpool}
	then
		err 1 "Pool already imported"
	fi

	zfs_encrypted_geli_attach ${zpool}
	zfs_encrypted_import_zpool ${zpool}
}

zfs_encrypted_stop_zpool(){
	zpool="$1"
	# Set cachefile none to prevent automount on boot
	zpool set cachefile=none ${zpool}
}

zfs_encrypted_start(){
	info "Starting ${name}"

	if [ $# -gt 0 ]
	then
		zfs_encrypted_zpools="$@"
	fi

	for zpool in ${zfs_encrypted_zpools}
	do
		zfs_encrypted_start_zpool $zpool
	done
}

zfs_encrypted_stop(){
	info "Stopping ${name}"

	if [ $# -gt 0 ]
	then
		zfs_encrypted_zpools="$@"
	fi

	for zpool in ${zfs_encrypted_zpools}
	do
		zfs_encrypted_stop_zpool $zpool
	done
}

run_rc_command "$@"
